import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {times} from '@/app/catalog';
export const dynamic='force-dynamic';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
function db(){if(!env.DB)throw Error('Storage unavailable');return env.DB}
async function isAdmin(){const user=await getChatGPTUser();return user?.email.toLowerCase()==='silueemmanuel93@gmail.com'}
function validDate(s:unknown){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s}
export async function GET(request:Request){try{const u=new URL(request.url);const action=u.searchParams.get('action');if(action==='availability'){const [b,t]=await db().batch([db().prepare('SELECT date FROM blocked'),db().prepare('SELECT date,time FROM orders WHERE date >= ?').bind(new Date().toISOString().slice(0,10))]);return response({blocked:b.results,taken:t.results})}if(action==='track'){const code=u.searchParams.get('code')||'';if(!/^[a-f0-9-]{36}$/.test(code))return response({error:'Code de suivi invalide.'},400);const order=await db().prepare('SELECT model,date,time,pickup,status FROM orders WHERE code=?').bind(code).first();return order?response(order):response({error:'Aucune commande trouvée. Vérifiez votre code de suivi.'},404)}if(action==='admin'){if(!await isAdmin())return response({error:'Connectez-vous avec le compte administrateur silueemmanuel93@gmail.com pour accéder à cet espace.'},403);const [o,b]=await db().batch([db().prepare('SELECT id,model,name,email,phone,notes,date,time,pickup,status FROM orders ORDER BY date,time'),db().prepare('SELECT date FROM blocked ORDER BY date')]);return response({orders:o.results,blocked:b.results})}return response({error:'Requête inconnue.'},400)}catch(e){console.error(e);return response({error:'L’atelier est temporairement indisponible. Réessayez dans un instant.'},503)}}
export async function POST(request:Request){try{if(request.headers.get('origin')!==new URL(request.url).origin)return response({error:'Origine non autorisée.'},403);const b=await request.json() as any;const database=db();if(b.action==='book'){if(!Number.isInteger(b.model)||b.model<1||b.model>200||typeof b.name!=='string'||!b.name.trim()||b.name.length>100||typeof b.email!=='string'||!/^\S+@\S+\.\S+$/.test(b.email)||b.email.length>150||typeof b.phone!=='string'||!b.phone.trim()||b.phone.length>30||typeof b.notes!=='string'||b.notes.length>1000||!validDate(b.date)||!validDate(b.pickup)||!times.includes(b.time)||b.date<new Date().toISOString().slice(0,10)||b.pickup<b.date)return response({error:'Vérifiez vos coordonnées, la date, l’heure et le jour de retrait.'},400);
const id=crypto.randomUUID(),code=crypto.randomUUID();try{const r=await database.prepare('INSERT INTO orders (id,code,model,name,email,phone,notes,date,time,pickup,status) SELECT ?,?,?,?,?,?,?,?,?,?,0 WHERE NOT EXISTS (SELECT 1 FROM blocked WHERE date IN (?,?))').bind(id,code,b.model,b.name.trim(),b.email.trim(),b.phone.trim(),b.notes,b.date,b.time,b.pickup,b.date,b.pickup).run();if(!r.meta.changes)return response({error:'L’une de ces journées est bloquée. Choisissez une autre date.'},409)}catch(e:any){if(String(e).includes('UNIQUE'))return response({error:'Ce créneau vient d’être réservé. Choisissez une autre heure.'},409);throw e}return response({code,order:{model:b.model,date:b.date,time:b.time,pickup:b.pickup,status:0}},201)}
if(!await isAdmin())return response({error:'Accès administrateur requis.'},403);if(b.action==='block'||b.action==='unblock'){if(!validDate(b.date))return response({error:'Date invalide.'},400);await database.prepare(b.action==='block'?'INSERT OR IGNORE INTO blocked (date) VALUES (?)':'DELETE FROM blocked WHERE date=?').bind(b.date).run();return response({ok:true})}if(b.action==='status'){if(!Number.isInteger(b.status)||b.status<0||b.status>5||typeof b.id!=='string')return response({error:'Statut invalide.'},400);const r=await database.prepare('UPDATE orders SET status=? WHERE id=?').bind(b.status,b.id).run();return r.meta.changes?response({ok:true}):response({error:'Commande introuvable.'},404)}return response({error:'Action inconnue.'},400)}catch(e){console.error(e);return response({error:'Impossible d’enregistrer pour le moment. Vos informations sont conservées, réessayez.'},503)}}
