'use client';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Calendar} from '@/components/ui/calendar';
import {fr} from 'date-fns/locale';
import {format} from 'date-fns';
import {CalendarDays,MapPin,ArrowUpRight} from 'lucide-react';
import {Shop,Price,total,money} from '../catalog';
export type Api=(path:string,body?:any)=>Promise<any>;
export const today=()=>format(new Date(),'yyyy-MM-dd');
export function Pick({value,onChange,items,label}:{value:string,onChange:(s:string)=>void,items:string[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem value={i} key={i}>{i}</SelectItem>)}</SelectContent></Select>}
export function DateChoice({value,onChange,min,blocked,label}:{value:string,onChange:(s:string)=>void,min:string,blocked:string[],label:string}){return <details className="date-choice"><summary>{label}<span>{value||'Choisir'}<CalendarDays size={16}/></span></summary><Calendar mode="single" locale={fr} selected={value?new Date(value+'T12:00:00'):undefined} onSelect={d=>{if(d)onChange(format(d,'yyyy-MM-dd'))}} disabled={d=>format(d,'yyyy-MM-dd')<min||blocked.includes(format(d,'yyyy-MM-dd'))}/><p className="muted">Les journées indisponibles sont désactivées.</p></details>}
export function Pricing({price,currency}:{price:Price,currency:string}){return <div className="pricing"><p className="eyebrow">TARIFICATION DU MODÈLE</p><div className="price-total"><span>À partir de</span><strong>{money(total(price),currency)}</strong></div><dl><div><dt>Confection sur mesure</dt><dd>{money(price.labor,currency)}</dd></div><div><dt>Tissu</dt><dd>{price.fabric_included?money(price.fabric,currency):'À fournir / en supplément'}</dd></div><div><dt>Finitions</dt><dd>{price.finishing==null?'À préciser':money(price.finishing,currency)}</dd></div></dl><p className="muted">{price.notes||'Le prix final dépend du tissu, de la coupe et des finitions. Devis à valider au rendez-vous.'}</p></div>}
export function Visit({shop}:{shop:Shop}){const modes=[['driving','Voiture'],['transit','Transports'],['walking','À pied']];return <section className="visit"><div><p className="eyebrow">RENCONTRONS-NOUS</p><h2>À l’atelier, tout prend forme.</h2><p>Un moment pour parler de votre tenue,<br/>choisir les détails et prendre vos mesures.</p></div><div className="visit-info"><MapPin size={24}/><h3>NAYA · Atelier de couture</h3><p>{shop.address||'L’adresse de l’atelier sera communiquée ici.'}</p>{shop.hours&&<p>{shop.hours}</p>}{shop.phone&&<p>{shop.phone}</p>}{shop.directions_note&&<p className="muted">{shop.directions_note}</p>}{shop.address?<><span className="eyebrow">VENIR AVEC GOOGLE MAPS</span><div className="transport">{modes.map(([mode,label])=><a key={mode} target="_blank" rel="noreferrer" href={'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(shop.address)+'&travelmode='+mode}>{label}<ArrowUpRight size={14}/></a>)}</div></>:<p className="muted">Les itinéraires seront disponibles dès que l’adresse sera renseignée.</p>}</div></section>}
